import type { DiffChange, RiskResult } from "@/types/diff";
import type { AnalysisMode } from "@/lib/share/store";

export interface ExportData {
  mode:        AnalysisMode;
  changes:     DiffChange[];
  risk:        RiskResult;
  ai:          { summary: string; recommendations: string[] } | null;
  direction?:  string;
  /** Safe metadata only — never includes auth/credentials */
  requestMeta?: {
    urlA: string; methodA: string;
    urlB: string; methodB: string;
  };
}

/** Sanitize a string for safe Markdown output — prevent injection. */
function mdEscape(s: string): string {
  return s.replace(/[`*_[\]<>&]/g, (c) => `\\${c}`);
}

export function exportJson(data: ExportData): string {
  const safe = {
    exportedAt:  new Date().toISOString(),
    tool:        "DiffBeacon",
    mode:        data.mode,
    direction:   data.direction,
    risk:        data.risk,
    changes:     data.changes,
    ai:          data.ai,
    requestMeta: data.requestMeta,
    // Explicitly omit: auth, headers, bearer tokens, API keys
  };
  return JSON.stringify(safe, null, 2);
}

export function exportMarkdown(data: ExportData): string {
  const { mode, risk, changes, ai, direction, requestMeta } = data;

  const breaking = changes.filter((c) => ["CRITICAL", "HIGH"].includes(c.severity));
  const review   = changes.filter((c) => c.severity === "MEDIUM");
  const safe     = changes.filter((c) => ["LOW", "SAFE"].includes(c.severity));

  const lines: string[] = [];

  lines.push("# DiffBeacon Analysis Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Mode:** ${mode.toUpperCase()}`);
  if (direction) lines.push(`**Direction:** ${direction}`);
  if (requestMeta) {
    lines.push(`**Baseline:** \`${mdEscape(requestMeta.methodA)} ${mdEscape(requestMeta.urlA)}\``);
    lines.push(`**Candidate:** \`${mdEscape(requestMeta.methodB)} ${mdEscape(requestMeta.urlB)}\``);
  }
  lines.push("");

  lines.push("## Risk Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Risk Score | **${risk.score} / 100** |`);
  lines.push(`| Risk Level | **${risk.label}** |`);
  lines.push(`| Breaking Changes | ${breaking.length} |`);
  lines.push(`| Review Changes | ${review.length} |`);
  lines.push(`| Safe Changes | ${safe.length} |`);
  lines.push(`| Total Changes | ${changes.length} |`);
  lines.push("");

  if (changes.length > 0) {
    lines.push("## Detected Changes");
    lines.push("");
    lines.push("| Path | Kind | Severity | Compatibility | Reason |");
    lines.push("|------|------|----------|---------------|--------|");
    for (const c of changes) {
      const compat = (c as { compatibility?: string }).compatibility ?? "—";
      lines.push(
        `| \`${mdEscape(c.path)}\` | ${mdEscape(c.kind)} | ${mdEscape(c.severity)} | ${mdEscape(compat)} | ${mdEscape(c.reason)} |`,
      );
    }
    lines.push("");
  }

  if (ai) {
    lines.push("## AI Impact Analysis");
    lines.push("");
    lines.push(mdEscape(ai.summary));
    lines.push("");
    if (ai.recommendations.length > 0) {
      lines.push("### Recommended Actions");
      lines.push("");
      for (const rec of ai.recommendations) {
        lines.push(`- ${mdEscape(rec)}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [DiffBeacon](https://github.com/Abubakar-webmaker/diffbeacon)*");

  return lines.join("\n");
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
